命令稿啟動於 2018年03月11日 下午 10:37:50
]0;~/lab1
[32mfredd@DESKTOP-T6CA2NC [33m~/lab1[0m
$ ./lab1B[C[Cg++ lab1B.cpp[C[Cvim[C[C[C[C[C[C[C[C[C[C[C[C[6P./lab1B[C[Cvim lab1B.cpp[1PB.cpp[C[C[5P./lab1B[C[Cg++ -o lab1B lab1B.cpp[C[C[C[C[C[C[9Plab1B.cpp[C[C[C[C[C[C-o lab1B lab1B.cpp
]0;~/lab1
[32mfredd@DESKTOP-T6CA2NC [33m~/lab1[0m
$ g++ -o lab1B lab1B.cpp[C[C./lab1B[K
22
11
34
17
52
26
13
40
20
10
5
16
8
4
2
1
]0;~/lab1
[32mfredd@DESKTOP-T6CA2NC [33m~/lab1[0m
$ exit

命令稿已於 2018年03月11日 下午 10:38:52
 完成