命令稿啟動於 2018年03月 9日 下午 04:49:33
]0;~
[32mfredd@DESKTOP-T6CA2NC [33m~[0m
$ whoami
fredd
]0;~
[32mfredd@DESKTOP-T6CA2NC [33m~[0m
$ pwd
/home/fredd
]0;~
[32mfredd@DESKTOP-T6CA2NC [33m~[0m
$ git config -l
]0;~
[32mfredd@DESKTOP-T6CA2NC [33m~[0m
$ git clone https://github.com/E24066331/lab1.git
Cloning into 'lab1'...
warning: You appear to have cloned an empty repository.
]0;~
[32mfredd@DESKTOP-T6CA2NC [33m~[0m
$ exit

命令稿已於 2018年03月 9日 下午 04:53:26
 完成