命令稿啟動於 2018年03月 9日 下午 05:12:34
]0;~
[32mfredd@DESKTOP-T6CA2NC [33m~[0m
$ whon[Kmi[Csmi[1Pmiami
fredd
]0;~
[32mfredd@DESKTOP-T6CA2NC [33m~[0m
$ pwd
/home/fredd
]0;~
[32mfredd@DESKTOP-T6CA2NC [33m~[0m
$ git config -l
user.email=freddu8881@gmail.com
user.name=E24066331
]0;~
[32mfredd@DESKTOP-T6CA2NC [33m~[0m
$ git clone https://github.com/E24066331/lab1.git
Cloning into 'lab1'...
remote: Counting objects: 5, done.[K
remote: Compressing objects:  33% (1/3)   [Kremote: Compressing objects:  66% (2/3)   [Kremote: Compressing objects: 100% (3/3)   [Kremote: Compressing objects: 100% (3/3), done.[K
remote: Total 5 (delta 0), reused 3 (delta 0), pack-reused 0[K
Unpacking objects:  20% (1/5)   Unpacking objects:  40% (2/5)   Unpacking objects:  60% (3/5)   Unpacking objects:  80% (4/5)   Unpacking objects: 100% (5/5)   Unpacking objects: 100% (5/5), done.
]0;~
[32mfredd@DESKTOP-T6CA2NC [33m~[0m
$ exit

命令稿已於 2018年03月 9日 下午 05:13:45
 完成